import type { MentorProtegePair } from "@/lib/types";

/**
 * Illustrative SBA All Small Mentor-Protégé pairs. Names are plausibly
 * realistic but fictional — real agreements are not published publicly.
 */
export const MENTOR_PROTEGE_PAIRS: MentorProtegePair[] = [
  {
    id: "mpp-01",
    mentorName: "Leidos",
    mentorUEI: "A1B2C3D4E5F6",
    mentorCapabilities: ["541512", "541511", "541715"],
    mentorIndustry: "Defense IT",
    protegeName: "Arlington Defense Solutions LLC",
    protegeUEI: "K9L8M7N6P5Q4",
    protegeStage: "Established",
    agreementDate: "2024-03-12",
    programEndDate: "2030-03-11",
    jointVentureName: "Leidos-Arlington JV",
    focusAreas: ["DevSecOps", "Cloud Migration", "Zero-Trust Architecture"],
    outcomes: "Joint win on $42M Navy SPAWAR cloud modernization task order.",
  },
  {
    id: "mpp-02",
    mentorName: "Booz Allen Hamilton",
    mentorUEI: "B2C3D4E5F6G7",
    mentorCapabilities: ["541611", "541512"],
    mentorIndustry: "Management Consulting",
    protegeName: "Patriot Cyber Group",
    protegeUEI: "L8M7N6P5Q4R3",
    protegeStage: "New",
    agreementDate: "2025-01-08",
    programEndDate: "2031-01-07",
    focusAreas: ["Cyber Risk Management", "RMF Authorizations", "SOC Operations"],
    outcomes: "Protégé achieved CMMC Level 2 within 9 months.",
  },
  {
    id: "mpp-03",
    mentorName: "CACI International",
    mentorUEI: "C3D4E5F6G7H8",
    mentorCapabilities: ["541512", "541330"],
    mentorIndustry: "Intelligence Systems",
    protegeName: "Blackhawk Intel Services",
    protegeUEI: "M7N6P5Q4R3S2",
    protegeStage: "Established",
    agreementDate: "2023-09-21",
    programEndDate: "2029-09-20",
    jointVentureName: "CACI-Blackhawk JV",
    focusAreas: ["SIGINT Analysis", "Linguist Services", "TS/SCI Staffing"],
    outcomes: "Awarded 3 JV task orders totaling $78M across DIA / INSCOM.",
  },
  {
    id: "mpp-04",
    mentorName: "Jacobs Engineering",
    mentorUEI: "D4E5F6G7H8J9",
    mentorCapabilities: ["541330", "236220"],
    mentorIndustry: "Engineering / Construction",
    protegeName: "Meridian Vet Construction",
    protegeUEI: "N6P5Q4R3S2T1",
    protegeStage: "New",
    agreementDate: "2025-05-04",
    programEndDate: "2031-05-03",
    focusAreas: ["MILCON", "Design-Build", "MEP Engineering"],
    outcomes: "Mentor provided bonding guarantees enabling $8M VA clinic bid.",
  },
  {
    id: "mpp-05",
    mentorName: "SAIC",
    mentorUEI: "E5F6G7H8J9K0",
    mentorCapabilities: ["541512", "541519"],
    mentorIndustry: "Federal IT",
    protegeName: "Valor Systems Inc",
    protegeUEI: "P5Q4R3S2T1U0",
    protegeStage: "Established",
    agreementDate: "2024-07-15",
    programEndDate: "2030-07-14",
    jointVentureName: "SAIC-Valor Partners",
    focusAreas: ["Enterprise IT Modernization", "AI/ML Ops"],
    outcomes: "JV shortlisted on Army ITES-4S recompete pool.",
  },
  {
    id: "mpp-06",
    mentorName: "ManTech",
    mentorUEI: "F6G7H8J9K0L1",
    mentorCapabilities: ["541512", "541715"],
    mentorIndustry: "Mission IT / R&D",
    protegeName: "Sentinel Strategic Group",
    protegeUEI: "Q4R3S2T1U0V9",
    protegeStage: "New",
    agreementDate: "2025-02-18",
    programEndDate: "2031-02-17",
    focusAreas: ["Counter-UAS", "Mission Engineering", "Prototyping"],
    outcomes: "Protégé won first DoD SBIR Phase II ($2.1M).",
  },
  {
    id: "mpp-07",
    mentorName: "General Dynamics IT",
    mentorUEI: "G7H8J9K0L1M2",
    mentorCapabilities: ["541512", "517311"],
    mentorIndustry: "Federal IT / Comms",
    protegeName: "Semper Digital LLC",
    protegeUEI: "R3S2T1U0V9W8",
    protegeStage: "Established",
    agreementDate: "2023-11-30",
    programEndDate: "2029-11-29",
    focusAreas: ["Network Engineering", "SATCOM", "Field Support"],
    outcomes: "Joint subcontract flow of $16M across 5 Army task orders.",
  },
  {
    id: "mpp-08",
    mentorName: "KBR",
    mentorUEI: "H8J9K0L1M2N3",
    mentorCapabilities: ["561210", "541330"],
    mentorIndustry: "Logistics / Facilities",
    protegeName: "Freedom Logistics Partners",
    protegeUEI: "S2T1U0V9W8X7",
    protegeStage: "Established",
    agreementDate: "2024-10-01",
    programEndDate: "2030-09-30",
    jointVentureName: "KBR-Freedom Logistics JV",
    focusAreas: ["LOGCAP", "Base Operations Support", "Contingency Logistics"],
    outcomes: "JV awarded $34M DLA disposition services BPA.",
  },
  {
    id: "mpp-09",
    mentorName: "Accenture Federal Services",
    mentorUEI: "J9K0L1M2N3P4",
    mentorCapabilities: ["541512", "541611"],
    mentorIndustry: "Digital Transformation",
    protegeName: "Eagle Crest Technologies",
    protegeUEI: "T1U0V9W8X7Y6",
    protegeStage: "New",
    agreementDate: "2025-06-22",
    programEndDate: "2031-06-21",
    focusAreas: ["Low-Code Platforms", "Human-Centered Design", "API Strategy"],
    outcomes: "Protégé launched first HHS USDS-aligned pilot.",
  },
  {
    id: "mpp-10",
    mentorName: "Peraton",
    mentorUEI: "K0L1M2N3P4Q5",
    mentorCapabilities: ["541512", "541715"],
    mentorIndustry: "Intel / Space",
    protegeName: "Trident Federal Inc",
    protegeUEI: "U0V9W8X7Y6Z5",
    protegeStage: "Established",
    agreementDate: "2024-04-09",
    programEndDate: "2030-04-08",
    focusAreas: ["Space Ground Systems", "Ground-Based Sensors"],
    outcomes: "Joint capture on SDA T2TL tracking layer bid.",
  },
  {
    id: "mpp-11",
    mentorName: "ICF International",
    mentorUEI: "L1M2N3P4Q5R6",
    mentorCapabilities: ["541611", "541990"],
    mentorIndustry: "Health / Environment Consulting",
    protegeName: "Old Glory Consulting",
    protegeUEI: "V9W8X7Y6Z5A4",
    protegeStage: "New",
    agreementDate: "2025-03-17",
    programEndDate: "2031-03-16",
    focusAreas: ["Public Health Analytics", "Environmental Compliance"],
    outcomes: "First HHS CDC task win — $4.8M.",
  },
  {
    id: "mpp-12",
    mentorName: "AECOM",
    mentorUEI: "M2N3P4Q5R6S7",
    mentorCapabilities: ["236220", "541330"],
    mentorIndustry: "Construction Management",
    protegeName: "Tidewater Defense Works",
    protegeUEI: "W8X7Y6Z5A4B3",
    protegeStage: "Established",
    agreementDate: "2023-08-14",
    programEndDate: "2029-08-13",
    jointVentureName: "AECOM-Tidewater JV",
    focusAreas: ["Waterfront MILCON", "Dry Dock Rehabilitation"],
    outcomes: "JV awarded $61M NAVFAC MACC task order.",
  },
  {
    id: "mpp-13",
    mentorName: "Parsons Corporation",
    mentorUEI: "N3P4Q5R6S7T8",
    mentorCapabilities: ["541330", "541512"],
    mentorIndustry: "Cyber / Infrastructure",
    protegeName: "Ironclad Federal Group",
    protegeUEI: "X7Y6Z5A4B3C2",
    protegeStage: "New",
    agreementDate: "2025-07-01",
    programEndDate: "2031-06-30",
    focusAreas: ["OT / ICS Cybersecurity", "Infrastructure Resilience"],
    outcomes: "Joint award on CISA critical infrastructure assessment IDIQ.",
  },
  {
    id: "mpp-14",
    mentorName: "Deloitte Federal",
    mentorUEI: "P4Q5R6S7T8U9",
    mentorCapabilities: ["541611", "541512"],
    mentorIndustry: "Federal Advisory",
    protegeName: "Veterans Analytics Corp",
    protegeUEI: "Y6Z5A4B3C2D1",
    protegeStage: "Established",
    agreementDate: "2024-01-23",
    programEndDate: "2030-01-22",
    focusAreas: ["Data Analytics", "Financial Management Modernization"],
    outcomes: "3 joint task orders across Treasury / VA totaling $22M.",
  },
  {
    id: "mpp-15",
    mentorName: "Northrop Grumman Mission Systems",
    mentorUEI: "Q5R6S7T8U9V0",
    mentorCapabilities: ["541712", "541330"],
    mentorIndustry: "Aerospace / Mission Systems",
    protegeName: "Honor Guard Engineering",
    protegeUEI: "Z5A4B3C2D1E0",
    protegeStage: "New",
    agreementDate: "2025-04-11",
    programEndDate: "2031-04-10",
    focusAreas: ["Systems Engineering", "Model-Based Systems Engineering"],
    outcomes: "Protégé hired 12 engineers under mentor workshare flow.",
  },
];
