import type { ProtegeProfile } from "@/lib/types";

export const PROTEGES_SEEKING: ProtegeProfile[] = [
  { id: "p-01", name: "Arlington Defense Solutions LLC", certifications: ["SDVOSB", "CMMC L2"], currentRevenue: "$12.5M", targetAgencies: ["Navy", "Army", "VA"], goals: ["Win $10M+ prime contract", "Expand cleared staff"], readinessScore: 88, primaryNAICS: "541512" },
  { id: "p-02", name: "Patriot Cyber Group", certifications: ["SDVOSB", "FedRAMP Mod"], currentRevenue: "$7.8M", targetAgencies: ["DHS", "DoD"], goals: ["CMMC L3 path", "Recompete DHS CDM"], readinessScore: 81, primaryNAICS: "541512" },
  { id: "p-03", name: "Liberty Federal Services", certifications: ["VOSB"], currentRevenue: "$3.4M", targetAgencies: ["GSA", "VA"], goals: ["Enter GSA MAS", "First prime win"], readinessScore: 62, primaryNAICS: "541611" },
  { id: "p-04", name: "Valor Systems Inc", certifications: ["SDVOSB", "ISO 9001"], currentRevenue: "$24M", targetAgencies: ["Army", "AF"], goals: ["JV for Army ITES-4S"], readinessScore: 92, primaryNAICS: "541512" },
  { id: "p-05", name: "Sentinel Strategic Group", certifications: ["SDVOSB"], currentRevenue: "$1.2M", targetAgencies: ["AF", "SOCOM"], goals: ["Graduate SBIR Phase II"], readinessScore: 55, primaryNAICS: "541715" },
  { id: "p-06", name: "Freedom Logistics Partners", certifications: ["SDVOSB", "ISO 9001"], currentRevenue: "$12.5M", targetAgencies: ["DLA", "Army"], goals: ["LOGCAP V subcontract flow"], readinessScore: 79, primaryNAICS: "561210" },
  { id: "p-07", name: "Eagle Crest Technologies", certifications: ["SDVOSB"], currentRevenue: "$3.4M", targetAgencies: ["HHS", "VA"], goals: ["Low-code platform win"], readinessScore: 66, primaryNAICS: "541512" },
  { id: "p-08", name: "Minuteman Engineering", certifications: ["VOSB"], currentRevenue: "$7.8M", targetAgencies: ["USACE", "NAVFAC"], goals: ["A/E schedule"], readinessScore: 71, primaryNAICS: "541330" },
  { id: "p-09", name: "Semper Digital LLC", certifications: ["SDVOSB"], currentRevenue: "$1.2M", targetAgencies: ["DoD"], goals: ["SATCOM task flow from GDIT"], readinessScore: 58, primaryNAICS: "541512" },
  { id: "p-10", name: "Bravo Federal Consulting", certifications: ["SDVOSB", "8(a)"], currentRevenue: "$3.4M", targetAgencies: ["Treasury", "HHS"], goals: ["Financial mgmt modernization"], readinessScore: 74, primaryNAICS: "541611" },
  { id: "p-11", name: "Anchor Point Solutions", certifications: ["VOSB"], currentRevenue: "$1.2M", targetAgencies: ["VA", "GSA"], goals: ["First federal prime"], readinessScore: 48, primaryNAICS: "541611" },
  { id: "p-12", name: "Pathfinder Federal LLC", certifications: ["SDVOSB"], currentRevenue: "$7.8M", targetAgencies: ["Army", "DHS"], goals: ["Data analytics capture"], readinessScore: 70, primaryNAICS: "541512" },
  { id: "p-13", name: "Gallant Shield Security", certifications: ["SDVOSB"], currentRevenue: "$24M", targetAgencies: ["DHS", "DoE"], goals: ["Guard services recompete"], readinessScore: 83, primaryNAICS: "561612" },
  { id: "p-14", name: "Rally Point Systems", certifications: ["SDVOSB", "CMMI L3"], currentRevenue: "$12.5M", targetAgencies: ["AF", "Space Force"], goals: ["Space ground systems JV"], readinessScore: 77, primaryNAICS: "541715" },
  { id: "p-15", name: "Ironclad Federal Group", certifications: ["SDVOSB"], currentRevenue: "$3.4M", targetAgencies: ["CISA", "DoE"], goals: ["OT cyber capture"], readinessScore: 68, primaryNAICS: "541330" },
  { id: "p-16", name: "Tidewater Defense Works", certifications: ["SDVOSB"], currentRevenue: "$24M", targetAgencies: ["NAVFAC"], goals: ["Waterfront MILCON JV"], readinessScore: 86, primaryNAICS: "236220" },
  { id: "p-17", name: "Summit Vet Consulting", certifications: ["VOSB"], currentRevenue: "$1.2M", targetAgencies: ["VA", "HHS"], goals: ["Enter 8(a) pipeline"], readinessScore: 50, primaryNAICS: "541611" },
  { id: "p-18", name: "Blackhawk Intel Services", certifications: ["SDVOSB", "TS/SCI"], currentRevenue: "$12.5M", targetAgencies: ["INSCOM", "DIA"], goals: ["Linguist JV growth"], readinessScore: 84, primaryNAICS: "541512" },
  { id: "p-19", name: "Meridian Vet Construction", certifications: ["SDVOSB"], currentRevenue: "$7.8M", targetAgencies: ["VA", "USACE"], goals: ["Bonding uplift to $10M"], readinessScore: 65, primaryNAICS: "236220" },
  { id: "p-20", name: "Keystone Ops Group", certifications: ["VOSB"], currentRevenue: "$3.4M", targetAgencies: ["DoD"], goals: ["Base ops recompete"], readinessScore: 60, primaryNAICS: "561210" },
  { id: "p-21", name: "Trident Federal Inc", certifications: ["SDVOSB"], currentRevenue: "$12.5M", targetAgencies: ["Space Force"], goals: ["SDA T2TL capture"], readinessScore: 80, primaryNAICS: "541715" },
  { id: "p-22", name: "Granite Peak IT", certifications: ["SDVOSB"], currentRevenue: "$1.2M", targetAgencies: ["HHS"], goals: ["First $1M+ prime"], readinessScore: 46, primaryNAICS: "541512" },
  { id: "p-23", name: "Stars and Stripes Tech", certifications: ["SDVOSB", "FedRAMP Mod"], currentRevenue: "$3.4M", targetAgencies: ["Treasury", "DoD"], goals: ["Commercial cloud reseller"], readinessScore: 67, primaryNAICS: "541512" },
  { id: "p-24", name: "Checkpoint Federal Services", certifications: ["VOSB"], currentRevenue: "$7.8M", targetAgencies: ["DHS"], goals: ["Screening services capture"], readinessScore: 63, primaryNAICS: "561612" },
  { id: "p-25", name: "Ridgeline Cyber", certifications: ["SDVOSB"], currentRevenue: "$3.4M", targetAgencies: ["DoD", "CISA"], goals: ["Red team services"], readinessScore: 72, primaryNAICS: "541512" },
  { id: "p-26", name: "Bulwark Defense LLC", certifications: ["SDVOSB"], currentRevenue: "$12.5M", targetAgencies: ["Army"], goals: ["MILCON path"], readinessScore: 75, primaryNAICS: "236220" },
  { id: "p-27", name: "Old Glory Consulting", certifications: ["SDVOSB"], currentRevenue: "$1.2M", targetAgencies: ["HHS", "EPA"], goals: ["Health analytics pilot"], readinessScore: 52, primaryNAICS: "541611" },
  { id: "p-28", name: "Veterans Analytics Corp", certifications: ["SDVOSB"], currentRevenue: "$24M", targetAgencies: ["Treasury", "VA"], goals: ["FMM modernization lead"], readinessScore: 89, primaryNAICS: "541512" },
  { id: "p-29", name: "Citadel Federal Group", certifications: ["SDVOSB", "8(a)"], currentRevenue: "$7.8M", targetAgencies: ["DHS", "DoJ"], goals: ["Law enforcement IT"], readinessScore: 73, primaryNAICS: "541512" },
  { id: "p-30", name: "Honor Guard Engineering", certifications: ["SDVOSB"], currentRevenue: "$3.4M", targetAgencies: ["AF"], goals: ["MBSE pipeline growth"], readinessScore: 69, primaryNAICS: "541330" },
];
